In [145]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [161]:
df_master = pd.read_csv("../../../data/initial_dataset/Master_04_10_2019.csv",sep=",",low_memory=False)
df_master = df_master.drop(df_master.columns[[0,1]],1)
df_itd = pd.read_csv("../../../data/updated_dataset/ITD_merge_updated.csv",sep=",",low_memory=False)
df_itd = df_itd.drop(df_itd.columns[0],1)

### I- Inconsistency in Master original DataFrame

data pd and sample pd are different!

In [162]:
df_master.loc[~(df_master['data_pd'] == df_master['sample_pd.x'])].head()
## All those are not consistent. I printed only the head.

,data_pd,sample_pd.x,ASXL1,ASXL2,ASXL3,ATRX,BAGE3,BCOR,BRAF,CBFB,...,MRD_relapse_status,CRdate,randDate_PB,CRDate_PB,relapseDate_PB,boneDate_PB,longCR_PB,FLT3_ITD_New,FLT3_ITD_Value_New,NoMatchFLT3
196,PD15056a,PD14961c,1,0,0,0,0,0,0,0,...,1.0,2007-09-20,0,0,0,0,0,0.0,NaN,Match
197,PD15044c,PD14973c,0,0,0,0,0,0,0,0,...,1.0,2007-08-15,0,0,0,0,0,NaN,NaN,Missing
373,PD15420a2,PD15420a,0,0,0,0,0,0,0,0,...,0.0,2011-01-19,0,0,0,0,0,0.0,NaN,Match
553,PD14996a,PD15021c,0,0,0,0,0,0,0,0,...,1.0,2007-11-01,0,0,0,0,0,0.0,NaN,Match
554,PD14984c,PD15033a,0,0,0,0,0,0,0,0,...,1.0,2007-08-10,0,0,0,0,0,NaN,NaN,Missing

### II- Checking dims of the datasets before and after the merge

##### We will lose one row after the merge

In [163]:
print('Master dimensions: '+str(df_master.shape))
print('ITD dimensions: '+str(df_itd.shape))
df_merge = pd.merge(df_master,df_itd, on='data_pd', how='inner')
print('Merge dimensions: '+str(df_merge.shape))

Master dimensions: (2428, 520)
ITD dimensions: (2445, 19)
Merge dimensions: (2427, 538)

##### Let's look at the missing row in the merge from Master

In [164]:
df_master[~df_master.data_pd.isin(df_merge.data_pd.unique())]

,data_pd,sample_pd.x,ASXL1,ASXL2,ASXL3,ATRX,BAGE3,BCOR,BRAF,CBFB,...,MRD_relapse_status,CRdate,randDate_PB,CRDate_PB,relapseDate_PB,boneDate_PB,longCR_PB,FLT3_ITD_New,FLT3_ITD_Value_New,NoMatchFLT3
37,PD22517d,PD22517d,0,0,0,0,0,0,0,0,...,0.0,2004-03-02,0,0,0,0,0,NaN,NaN,Missing

##### Let's look at the missing rows(18 of them) in the merge from ITD

In [165]:
df_itd[~df_itd.data_pd.isin(df_merge.data_pd.unique())]

,data_pd,sample_pd,IID,Read_count,Insertion_pt,Length,Inserted_sequence,Microhomology,NTS,Num_ITDs,Second_ITD,donor_id,NGS_ITD,Clin_ITD,Clin_Ratio,Merge_ITD,Merge_ITD_Ratio,Calledby,Merge_ITD_new_rules
3,PD15032c,PD14985a,PD14985,104.0,13:28608288,75.0,ACTACCAAACTCTAAATTTTCTCTTGGAAACTCCCATTTGAGATCA...,.,AC,4,32___13:28608273___24___TTTGAGATCATATTCATATTCT...,16-1187,1.0,NaN,NaN,1.0,na,NGS_na,1.0
4,PD15035a2,PD15035a,PD15035,185.0,13:28608286,30.0,TCATATTCATATTCTCTGAAATCAACGTAG,.,.,5,12___13:28608322___48___GAATCAACGTAGAAGTACTCAT...,17-2818,1.0,NaN,NaN,1.0,na,NGS_na,1.0
5,PD15038a,PD14979a,PD14979,61.0,13:28608319,69.0,GTGAGATCATATTCATATTCTCTGAAATCAACGTAGAAGTACTCAT...,.,G,2,12___13:28608319___57___TCATATTCTCTGAAATCAACGT...,17-2840,1.0,NaN,NaN,1.0,na,NGS_na,0.0
6,PD15028a2,PD15028a,PD15028,101.0,13:28608301,42.0,CTTTCATATTCTCTGAAATCAACGTAGAAGTACTCATTATCT,.,CT,2,7___13:28608534___380___CATTTTAAAGATTTTCCAATGG...,17-2891,1.0,NaN,NaN,1.0,na,NGS_na,1.0
7,PD14998a,PD15019c,PD15019,163.0,13:28608313,75.0,GGAAACTCCCATTTGAGATCATATTCATATTCTCTGAAATCAACGT...,.,.,1,.,17-2999,1.0,NaN,NaN,1.0,na,NGS_na,1.0
12,PD14994c,PD15023a,PD15023,8.0,13:28608281,21.0,ATTCATATTCTCTGAAATCAA,.,.,1,.,Li1-1073,1.0,NaN,NaN,1.0,na,NGS_na,0.0
55,PD20144c,PD20144c,PD20144,NaN,.,NaN,.,.,.,0,.,16-1231,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
56,PD15065c,PD15065c,PD15065,NaN,.,NaN,.,.,.,0,.,16-5833,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
57,PD19988c,PD19988c,PD19988,NaN,.,NaN,.,.,.,0,.,16-5863,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
58,PD15048a,PD15048a,PD15048,NaN,.,NaN,.,.,.,0,.,17-2823,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
59,PD15050c,PD14967a,PD14967,NaN,.,NaN,.,.,.,0,.,17-2855,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
60,PD15050c2,PD15050c,PD15050,NaN,.,NaN,.,.,.,0,.,17-2857,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
61,PD23131c,PD23131c,PD23131,NaN,.,NaN,.,.,.,0,.,17-2859,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
62,PD15048c,PD14969a,PD14969,NaN,.,NaN,.,.,.,0,.,17-2887,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
99,PD15055c,PD14962c,PD14962,NaN,.,NaN,.,.,.,0,.,LI1-1074,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
107,PD14965c,PD15052c,PD15052,NaN,.,NaN,.,.,.,0,.,Li1-1090,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
571,PD14989c2,PD14989c,PD14989,303.0,13:28608286,42.0,TCCCATTTGAGATCATATTCATATTCTCTGAAATCAACGTAG,.,.,2,13___13:28608286___309___TCCCATTTTTGTGCATCTTTG...,17-2828,1.0,1.0,17.4,1.0,NaN,Both,1.0
697,PD14979a,PD15038a,PD15038,NaN,.,NaN,.,.,.,0,.,17-2847,0.0,1.0,24.0,1.0,NaN,CLIN,1.0

From the 18 rows of the ITD dataset that I could not merge with the master dataset , 13 of them were already spotted in the ITD inconsistency analysis because sample_pd and data_pd were different. Let's look at them on the ITD dataset

In [166]:
tmp=df_itd.loc[~(df_itd['data_pd'] == df_itd['sample_pd'])]
tmp[tmp.index.isin(df_itd[~df_itd.data_pd.isin(df_merge.data_pd.unique())].index.unique())]

,data_pd,sample_pd,IID,Read_count,Insertion_pt,Length,Inserted_sequence,Microhomology,NTS,Num_ITDs,Second_ITD,donor_id,NGS_ITD,Clin_ITD,Clin_Ratio,Merge_ITD,Merge_ITD_Ratio,Calledby,Merge_ITD_new_rules
3,PD15032c,PD14985a,PD14985,104.0,13:28608288,75.0,ACTACCAAACTCTAAATTTTCTCTTGGAAACTCCCATTTGAGATCA...,.,AC,4,32___13:28608273___24___TTTGAGATCATATTCATATTCT...,16-1187,1.0,NaN,NaN,1.0,na,NGS_na,1.0
4,PD15035a2,PD15035a,PD15035,185.0,13:28608286,30.0,TCATATTCATATTCTCTGAAATCAACGTAG,.,.,5,12___13:28608322___48___GAATCAACGTAGAAGTACTCAT...,17-2818,1.0,NaN,NaN,1.0,na,NGS_na,1.0
5,PD15038a,PD14979a,PD14979,61.0,13:28608319,69.0,GTGAGATCATATTCATATTCTCTGAAATCAACGTAGAAGTACTCAT...,.,G,2,12___13:28608319___57___TCATATTCTCTGAAATCAACGT...,17-2840,1.0,NaN,NaN,1.0,na,NGS_na,0.0
6,PD15028a2,PD15028a,PD15028,101.0,13:28608301,42.0,CTTTCATATTCTCTGAAATCAACGTAGAAGTACTCATTATCT,.,CT,2,7___13:28608534___380___CATTTTAAAGATTTTCCAATGG...,17-2891,1.0,NaN,NaN,1.0,na,NGS_na,1.0
7,PD14998a,PD15019c,PD15019,163.0,13:28608313,75.0,GGAAACTCCCATTTGAGATCATATTCATATTCTCTGAAATCAACGT...,.,.,1,.,17-2999,1.0,NaN,NaN,1.0,na,NGS_na,1.0
12,PD14994c,PD15023a,PD15023,8.0,13:28608281,21.0,ATTCATATTCTCTGAAATCAA,.,.,1,.,Li1-1073,1.0,NaN,NaN,1.0,na,NGS_na,0.0
59,PD15050c,PD14967a,PD14967,NaN,.,NaN,.,.,.,0,.,17-2855,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
60,PD15050c2,PD15050c,PD15050,NaN,.,NaN,.,.,.,0,.,17-2857,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
62,PD15048c,PD14969a,PD14969,NaN,.,NaN,.,.,.,0,.,17-2887,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
99,PD15055c,PD14962c,PD14962,NaN,.,NaN,.,.,.,0,.,LI1-1074,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
107,PD14965c,PD15052c,PD15052,NaN,.,NaN,.,.,.,0,.,Li1-1090,0.0,NaN,NaN,0.0,NaN,NGS_na,0.0
571,PD14989c2,PD14989c,PD14989,303.0,13:28608286,42.0,TCCCATTTGAGATCATATTCATATTCTCTGAAATCAACGTAG,.,.,2,13___13:28608286___309___TCCCATTTTTGTGCATCTTTG...,17-2828,1.0,1.0,17.4,1.0,NaN,Both,1.0
697,PD14979a,PD15038a,PD15038,NaN,.,NaN,.,.,.,0,.,17-2847,0.0,1.0,24.0,1.0,NaN,CLIN,1.0

### III- Set up the dataframe including genomics and translocations data for the clustering

For the translocation features, we do not want to keep all the features. Instead, what we want to do is to look at the frequency and keep only those with high frequency .
Regarding additions and deletions, we have set up some rules in order to reduce the number of features and therefore to be less prone to overfitting

#### I- Data Frame with all genomics and all translocation features

#### Let's first look at when ITD new rules and FLT3 ITD diverge

In [233]:
tmp_itd = df_merge.loc[:,['Merge_ITD_new_rules','FLT3_ITD','Merge_ITD']]
tmp_itd=tmp_itd[tmp_itd.Merge_ITD_new_rules!=tmp_itd.FLT3_ITD]
print ('They diverge in '+str(tmp_itd.shape[0])+ ' rows')

They diverge in 152 rows

#### Let's  look at when ITD initial rules and FLT3 ITD diverge

In [236]:
tmp_itd = df_merge.loc[:,['Merge_ITD_new_rules','FLT3_ITD','Merge_ITD']]
tmp_itd=tmp_itd[tmp_itd.Merge_ITD!=tmp_itd.FLT3_ITD]
print ('They diverge in '+str(tmp_itd.shape[0])+ ' rows')

They diverge in 49 rows

In [168]:
df_w_transloc = df_merge.loc[:,'ASXL1':'ZRSR2']
print ('number of genomic features: '+str(df_w_transloc.shape[1]))
df_w_transloc=df_w_transloc.join(df_merge.loc[:,'t_v_11':'complex'])
print ('number of translocation features: '+str(df_merge.loc[:,'t_v_11':'complex'].shape[1]))
print ('number of genomic + translocation features: '+ str(df_w_transloc.shape[1]))
df_w_transloc = df_merge.loc[:,['data_pd','sample_pd']].join(df_w_transloc)
print ('number of genomic + translocation features + id features: '+ str(df_w_transloc.shape[1]))

number of genomic features: 83
number of translocation features: 355
number of genomic + translocation features: 438
number of genomic + translocation features + id features: 440

#### Let's replace FLT3_ITD by Merge_ITD_new_rules

In [169]:
print(sum(df_w_transloc['FLT3_ITD']))
df_w_transloc['FLT3_ITD'] = df_merge['Merge_ITD_new_rules']
print(sum(df_w_transloc['FLT3_ITD']))
df_w_transloc.rename(columns={'FLT3_ITD':'ITD'},inplace=True)
print (df_w_transloc.shape)

609
503.0
(2427, 440)

Let's get rid of NaN rows that are present because of NaN values in the translocation features

In [139]:
print('There are '+str(df_w_transloc[df_w_transloc.t_13_19.isna()].shape[0])+' rows with Nan values in the translocation features')

There are 277 rows with Nan values in the translocation features

##### Let's get rid of them (unfortunately the size of the dataset is going to decrease by those number of rows)

##### The final dataset without those NaN values and with all genomics and translocation features is as follow: (we also save it)

In [172]:
df_w_transloc = df_w_transloc[~df_w_transloc.t_13_19.isna()]
df_w_transloc.shape
#df_w_transloc.reset_index(inplace=True)  ## maybe i should reset indexes?
#df_w_transloc.to_csv("../../../data/updated_dataset/merge_gene_w_all_transloc_updated.csv",sep=",")

(2150, 440)

# I-New RULES FRIDAY APRIL 19 and 22 Post meeting with Elli

## I-1 Additions

In [238]:
tmp_add = df_w_transloc.loc[:,'add_10p':'add_xq']
tmp_add = pd.concat([tmp_add,df_w_transloc.loc[:,'plus1':'plusy']],1)
to_keep = []
for i in range(1,23):
    tmp_add['add_'+str(i)] = tmp_add['add_'+str(i)+'p']+tmp_add['add_'+str(i)+'q']+tmp_add['plus'+str(i)]
    freq = 100*sum(tmp_add['add_'+str(i)])/tmp_add.shape[0]
    print ('Chromosome : '+str(i)+' with Freqency(%)', freq)
    to_keep +=['add_'+str(i) if freq >=2 else '']
    
tmp_add['add_x'] = tmp_add['add_xp']+tmp_add['add_xq']+tmp_add['plusx']
freq = 100*sum(tmp_add['add_x'])/tmp_add.shape[0]
print ('Chromosome : x with Freqency(%)', freq)
to_keep +=['add_x' if freq >=2 else '']

freq = 100*sum(tmp_add['plusy'])/tmp_add.shape[0]
print ('Chromosome : y with Freqency(%)', freq)
to_keep +=['plusy' if freq >=2 else '']


to_keep= [t for t in to_keep if t!='']
print()
print('We keep : '+ str(to_keep))
tmp_add = tmp_add[to_keep]
tmp_add[tmp_add>1]=1

Chromosome : 1 with Freqency(%) 1.5348837209302326
Chromosome : 2 with Freqency(%) 0.9767441860465116
Chromosome : 3 with Freqency(%) 1.302325581395349
Chromosome : 4 with Freqency(%) 1.5813953488372092
Chromosome : 5 with Freqency(%) 0.8837209302325582
Chromosome : 6 with Freqency(%) 1.9534883720930232
Chromosome : 7 with Freqency(%) 1.3488372093023255
Chromosome : 8 with Freqency(%) 10.232558139534884
Chromosome : 9 with Freqency(%) 1.6744186046511629
Chromosome : 10 with Freqency(%) 0.9767441860465116
Chromosome : 11 with Freqency(%) 3.953488372093023
Chromosome : 12 with Freqency(%) 1.1627906976744187
Chromosome : 13 with Freqency(%) 2.2325581395348837
Chromosome : 14 with Freqency(%) 1.441860465116279
Chromosome : 15 with Freqency(%) 0.8372093023255814
Chromosome : 16 with Freqency(%) 1.069767441860465
Chromosome : 17 with Freqency(%) 1.6744186046511629
Chromosome : 18 with Freqency(%) 0.6976744186046512
Chromosome : 19 with Freqency(%) 1.8604651162790697
Chromosome : 20 with Freqency(%) 0.9767441860465116
Chromosome : 21 with Freqency(%) 3.7209302325581395
Chromosome : 22 with Freqency(%) 2.744186046511628
Chromosome : x with Freqency(%) 0.46511627906976744
Chromosome : y with Freqency(%) 0.27906976744186046

We keep : ['add_8', 'add_11', 'add_13', 'add_21', 'add_22']

## I-2 Deletions

In [240]:
tmp_del = df_w_transloc.loc[:,'del_10p':'del_xq']
tmp_del = pd.concat([tmp_del,df_w_transloc.loc[:,'minus1':'minusy']],1)
tmp_del.drop(['minus7.'],1,inplace=True)
to_keep = []
list_p_missing = ['4', '14', '20', '21', '22']
list_with_p = ['1', '2', '3', '5', '6', '7', '8', '9', '10', '11', '12', '13', '15', '16', '17', '18', '19',  ]
for l in list_p_missing:
    tmp_del['del_'+l] = tmp_del['del_'+l+'q'] + tmp_del['minus'+l]
    freq = 100*sum(tmp_del['del_'+l])/tmp_del.shape[0]
    print ('Chromosome : '+l+' with Freqency(%)', freq)
    to_keep +=['del_'+l if freq >=2 else '']
    
for l in list_with_p:
    tmp_del['del_'+l] = tmp_del['del_'+l+'p'] + tmp_del['del_'+l+'q'] + tmp_del['minus'+l]
    freq = 100*sum(tmp_del['del_'+l])/tmp_del.shape[0]
    print ('Chromosome : '+l+' with Freqency(%)', freq)
    to_keep +=['del_'+l if freq >=2 else '']
    
tmp_del['del_x'] = tmp_del['del_xq'] + tmp_del['minusx'] 
freq = 100*sum(tmp_del['del_x'])/tmp_del.shape[0]
to_keep +=['del_x' if freq >=2 else '']
print ('Chromosome : x with Freqency(%)', 100*sum(tmp_del['del_x'])/tmp_del.shape[0])

freq = 100*sum(tmp_del['minusy'])/tmp_del.shape[0]
to_keep +=['minusy' if freq >=2 else '']
print ('Chromosome : y with Freqency(%)', 100*sum(tmp_del['minusy'])/tmp_del.shape[0])

to_keep= [t for t in to_keep if t!='']
print()
print('We keep : '+ str(to_keep))
tmp_del = tmp_del[to_keep]
tmp_del[tmp_del>1]=1

Chromosome : 4 with Freqency(%) 1.3953488372093024
Chromosome : 14 with Freqency(%) 0.9767441860465116
Chromosome : 20 with Freqency(%) 2.744186046511628
Chromosome : 21 with Freqency(%) 1.5813953488372092
Chromosome : 22 with Freqency(%) 1.2093023255813953
Chromosome : 1 with Freqency(%) 0.6046511627906976
Chromosome : 2 with Freqency(%) 0.9767441860465116
Chromosome : 3 with Freqency(%) 2.13953488372093
Chromosome : 5 with Freqency(%) 7.162790697674419
Chromosome : 6 with Freqency(%) 1.2093023255813953
Chromosome : 7 with Freqency(%) 8.883720930232558
Chromosome : 8 with Freqency(%) 0.5116279069767442
Chromosome : 9 with Freqency(%) 3.0232558139534884
Chromosome : 10 with Freqency(%) 0.6511627906976745
Chromosome : 11 with Freqency(%) 1.6744186046511629
Chromosome : 12 with Freqency(%) 2.7906976744186047
Chromosome : 13 with Freqency(%) 2.186046511627907
Chromosome : 15 with Freqency(%) 1.1162790697674418
Chromosome : 16 with Freqency(%) 2.3255813953488373
Chromosome : 17 with Freqency(%) 3.5348837209302326
Chromosome : 18 with Freqency(%) 2.604651162790698
Chromosome : 19 with Freqency(%) 0.5581395348837209
Chromosome : x with Freqency(%) 1.3488372093023255
Chromosome : y with Freqency(%) 3.441860465116279

We keep : ['del_20', 'del_3', 'del_5', 'del_7', 'del_9', 'del_12', 'del_13', 'del_16', 'del_17', 'del_18', 'minusy']

## I-3 Others with translocations count >=2 + complex(frequency >2)

In [227]:
transloc = df_w_transloc.loc[:,'t_v_11':'complex']
#transloc.tail()
transloc.loc['count']=transloc.sum()
high_count = pd.DataFrame(transloc.loc['count'].T)
transloc_keep = high_count[(high_count['count']>=2) & ((high_count.index.str.contains("t_"))|(high_count.index=="complex"))].index
transloc_to_sum = high_count[(high_count['count']<2) & ((high_count.index.str.contains("t_")))].index
tmp_others = df_w_transloc.loc[:,transloc_keep]
tmp_others['others_transloc'] = transloc.loc[:,transloc_to_sum].sum(axis = 1)
tmp_others.others_transloc[tmp_others.others_transloc>1]=1
print(tmp_others.columns)
#tmp_others.others_transloc

Index(['t_v_11', 't_10_21', 't_12_13', 't_12_17', 't_12_22', 't_13_19',
       't_15_16', 't_15_17', 't_16_17', 't_16_21', 't_17_19', 't_17_21',
       't_1_12', 't_1_14', 't_1_16', 't_1_17', 't_1_19', 't_1_3', 't_1_4',
       't_1_5', 't_1_6', 't_2_17', 't_2_3', 't_2_5', 't_2_7', 't_2_9',
       't_3_16', 't_3_21', 't_3_5', 't_3_7', 't_3_9', 't_4_12', 't_4_21',
       't_4_9', 't_5_12', 't_5_17', 't_5_9', 't_6_9', 't_7_16', 't_7_17',
       't_7_8', 't_8_10', 't_8_13', 't_8_16', 't_8_17', 't_8_21', 't_9_11',
       't_9_13', 't_9_17', 't_9_22', 'complex', 'others_transloc'],
      dtype='object')

## I-4 All together in a datframe with other features

In [223]:
df_modif_final = df_w_transloc.loc[:,'data_pd':'ZRSR2']
print(df_modif_final.shape) # 83 genomic features + 2 ids features
df_modif_final = df_modif_final.join(tmp_add)
print(df_modif_final.shape) # + 5 translocation addition features
df_modif_final = df_modif_final.join(tmp_del) # + 11 deletion features
print(df_modif_final.shape)
df_modif_final = df_modif_final.join(tmp_others) # + 52 translocation features
print('Final df for clustering dimensions :'+str(df_modif_final.shape))

(2150, 85)
(2150, 90)
(2150, 101)
Final df for clustering dimensions :(2150, 153)

#### Let's look at the types of the variables to make it uniform

In [225]:
print(df_modif_final.dtypes.unique())
df_modif_final.iloc[:,2:] = df_modif_final.iloc[:,2:].astype(int)
print(df_modif_final.dtypes.unique())

[dtype('O') dtype('int64') dtype('float64')]
[dtype('O') dtype('int64')]

## Create the csv file

In [226]:
df_modif_final.to_csv("../../../data/updated_dataset/modif_final.csv",sep=",")

# STOP HERE (AFTER IT WAS FIRST RULES UNVALIDATED)

# II- First modification of the copies and translocation ( not to use anymore ...)

#### Let's look at the translocation features that never appear

In [13]:
transloc = df_w_transloc.loc[:,'t_v_11':'complex']
transloc.loc['Total']=transloc.sum()
pd.DataFrame(transloc.loc['Total'][transloc.loc['Total']==0])

           Total
del_13p      0.0
del_15p      0.0
del_18p      0.0
del_18q      0.0
dic_13_14    0.0
minus7.      0.0
t_17_22      0.0

#### Now, let's look at the one that appear frequently (more than 2%)

In [45]:
transloc = df_w_transloc.loc[:,'t_v_11':'complex']
#transloc.tail()
transloc.loc['High_Freq(>2%)']=transloc.sum()
high_freq = pd.DataFrame(transloc.loc['High_Freq(>2%)'].T)
high_freq[(high_freq['High_Freq(>2%)']>=2) & (high_freq.index.str.contains("t"))]

                        High_Freq(>2%)
t_v_11                            64.0
complex_translocations            14.0
t_10_21                            2.0
t_12_13                            2.0
t_12_17                            3.0
t_12_22                            6.0
t_13_19                            2.0
t_15_16                            2.0
t_15_17                           21.0
t_16_17                            5.0
t_16_21                            2.0
t_17_19                            3.0
t_17_21                            3.0
t_1_12                             2.0
t_1_14                             2.0
t_1_16                             4.0
t_1_17                             3.0
t_1_19                             2.0
t_1_3                              3.0
t_1_4                              4.0
t_1_5                              2.0
t_1_6                              2.0
t_2_17                             3.0
t_2_3                              2.0
t_2_5                              2.0
t_2_7                              2.0
t_2_9                              2.0
t_3_16                             4.0
t_3_21                             4.0
t_3_5                              2.0
t_3_7                              2.0
t_3_9                              2.0
t_4_12                             3.0
t_4_21                             2.0
t_4_9                              2.0
t_5_12                             2.0
t_5_17                             2.0
t_5_9                              3.0
t_6_9                             17.0
t_7_16                             2.0
t_7_17                             3.0
t_7_8                              2.0
t_8_10                             2.0
t_8_13                             3.0
t_8_16                             3.0
t_8_17                             4.0
t_8_21                           101.0
t_9_11                            32.0
t_9_13                             2.0
t_9_17                             2.0
t_9_22                             8.0

In [14]:
transloc = df_w_transloc.loc[:,'t_v_11':'complex']
#transloc.tail()
transloc.loc['High_Freq(>2%)']=(transloc.sum()/df_w_transloc.shape[0])*100
high_freq = pd.DataFrame(transloc.loc['High_Freq(>2%)'].T)
high_freq[high_freq['High_Freq(>2%)']>=2]

         High_Freq(>2%)
t_v_11         2.976744
del_5q         4.511628
del_7q         2.976744
del_9q         2.418605
inv_16         4.372093
mar            6.930233
minus17        3.302326
minus18        2.604651
minus5         2.604651
minus7         5.720930
minusy         3.441860
plus11         2.000000
plus21         2.930233
plus22         2.046512
plus8          9.441860
t_8_21         4.697674
complex       15.674419

### A) Translocation features Additions

#### We follow the rules that we have set up

In [15]:
t = df_w_transloc.loc[:,'add_10p':'add_xq']
t = pd.concat([t,df_w_transloc.loc[:,'plus1':'plusy']],1)
t.shape[1]

70

There are 70 features for the Additions: 23*2+24=70

23: add_ chromosome 1 to 22 and chromosome x

2: p and q

24: plus chromosome 1 to 22 and x and y

#### Let's prepare the rules

In [16]:
add = df_w_transloc.loc[:,'add_10p':'add_xq']
add = pd.concat([add,df_w_transloc.loc[:,'plus1':'plusy']],1)

lis = [1,2,3,4,5,6,7,9,10,12,13,14,15,16,17,18,19,20]  # basic rule

li = [8,11,21,22]  #rules for the ones with more than 2%

# we create the column merge to sum all of them and we drop the other columns : merge= p+q+plus
for l in lis:
    add['add_'+str(l)+'_merge']=add['add_'+str(l)+'p']+add['add_'+str(l)+'q']+add['plus'+str(l)]
    add.drop(['add_'+str(l)+'p','add_'+str(l)+'q','plus'+str(l)], axis=1,inplace=True)
    
# we create the column merge to sum the one with less than 2% frequency and we drop the columns used in the sum : merge = p+q
for l in li:
    add['add_'+str(l)+'_merge']=add['add_'+str(l)+'p']+add['add_'+str(l)+'q']
    add.drop(['add_'+str(l)+'p','add_'+str(l)+'q'], axis=1,inplace=True)
    
add['add_merge_x_y']=add['add_xp']+add['add_xq']+add['plusx']+add['plusy']    
add.drop(['add_xp','add_xq','plusx','plusy'], axis=1,inplace=True)

##### Let's check the number of features now: 
We should have 27 features for add because 18 from the lis + 4*2 from the li and 1 from xandy

In [17]:
add.shape[1]

27

##### Let's confirm that the rules are working with an example where add_merge should be greater than one

In [18]:
print (add[add.add_2_merge>1].index)
t[['add_2p','add_2q','plus2']].ix[1734]

Int64Index([1734], dtype='int64')

add_2p    1.0
add_2q    1.0
plus2     0.0
Name: 1734, dtype: float64

In [19]:
print(t[['add_xp','add_xq','plusx','plusy']].ix[11])
print(add['add_merge_x_y'].ix[11])

add_xp    1.0
add_xq    0.0
plusx     0.0
plusy     0.0
Name: 11, dtype: float64
1.0

### B) Translocation features Deletions

In [20]:
d = df_w_transloc.loc[:,'del_10p':'del_xq']
d = pd.concat([d, df_w_transloc.loc[:,'minus1':'minusy']],1)
d.drop(columns=['minus7.'],inplace=True)
d.shape[1]

64

##### There are 64 features instead of 70 because we are missing a few p in the deletions . I also deleted a weird column 'minus7.'

#### Let's prepare the rules

In [21]:
d.columns

Index(['del_10p', 'del_10q', 'del_11p', 'del_11q', 'del_12p', 'del_12q',
       'del_13p', 'del_13q', 'del_14q', 'del_15p', 'del_15q', 'del_16p',
       'del_16q', 'del_17p', 'del_17q', 'del_18p', 'del_18q', 'del_19p',
       'del_19q', 'del_1p', 'del_1q', 'del_20q', 'del_21q', 'del_22q',
       'del_2p', 'del_2q', 'del_3p', 'del_3q', 'del_4q', 'del_5p', 'del_5q',
       'del_6p', 'del_6q', 'del_7p', 'del_7q', 'del_8p', 'del_8q', 'del_9p',
       'del_9q', 'del_xq', 'minus1', 'minus10', 'minus11', 'minus12',
       'minus13', 'minus14', 'minus15', 'minus16', 'minus17', 'minus18',
       'minus19', 'minus2', 'minus20', 'minus21', 'minus22', 'minus3',
       'minus4', 'minus5', 'minus6', 'minus7', 'minus8', 'minus9', 'minusx',
       'minusy'],
      dtype='object')

##### We can notice that the 'p' is missing for 6 of the chromosomes so we will have to handle this : 4,14,20,21,22,x

In [22]:
deletion = df_w_transloc.loc[:,'del_10p':'del_xq']
deletion=pd.concat([deletion,df_w_transloc.loc[:,'minus1':'minusy']],1)
deletion.drop(['minus7.'],1,inplace=True)

lis = [1,2,3,6,8,10,11,12,13,15,16,19] # basic rule
lis_p_missing = [4,14,20,21,22] # when p is missing

for l in lis:
    deletion['del_'+str(l)+'_merge']=deletion['del_'+str(l)+'p']+deletion['del_'+str(l)+'q']+deletion['minus'+str(l)]
    deletion.drop(['del_'+str(l)+'p','del_'+str(l)+'q','minus'+str(l)], axis=1,inplace=True)

for l in lis_p_missing:
    deletion['del_'+str(l)+'_merge']=deletion['del_'+str(l)+'q']+deletion['minus'+str(l)]
    deletion.drop(['del_'+str(l)+'q','minus'+str(l)], axis=1,inplace=True) 

for l in [17,18]: # frequency of minus > 2%
    deletion['del_'+str(l)+'_merge']=deletion['del_'+str(l)+'p']+deletion['del_'+str(l)+'q']
    deletion.drop(['del_'+str(l)+'p','del_'+str(l)+'q'], axis=1,inplace=True)

for l in [5,7]: # frequency of q and minus > 2% : keep q and sum(p+minus) in a new column and delete the rest    
    deletion['del_'+str(l)+'_merge']=deletion['del_'+str(l)+'p']+deletion['minus'+str(l)]
    deletion.drop(['del_'+str(l)+'p','minus'+str(l)], axis=1,inplace=True)
    
# chromosome 9: freqency of q > 2% : keep q and sum(p+minus) in a new column and delete the rest
deletion['del_9_merge']=deletion['del_9p']+deletion['minus9']
deletion.drop(['del_9p','minus9'], axis=1,inplace=True)

# chromosome x and y: frequency of minusy > 2%: keep column minusy and sum(q+minusx) in new col and delete the rest (p is missing)
deletion['del_x_merge']=deletion['del_xq']+deletion['minusx']
deletion.drop(['del_xq','minusx'],axis=1,inplace=True)

##### We should now have 29 columns:
17 from basic rules including when p is missing
4 when freq of minus only > 2%
4 when freq of q and minus > 2%
2 when freq of q only > 2%
2 from x and y

In [23]:
deletion.shape[1]

29

In [24]:
deletion.columns

Index(['del_5q', 'del_7q', 'del_9q', 'minus17', 'minus18', 'minusy',
       'del_1_merge', 'del_2_merge', 'del_3_merge', 'del_6_merge',
       'del_8_merge', 'del_10_merge', 'del_11_merge', 'del_12_merge',
       'del_13_merge', 'del_15_merge', 'del_16_merge', 'del_19_merge',
       'del_4_merge', 'del_14_merge', 'del_20_merge', 'del_21_merge',
       'del_22_merge', 'del_17_merge', 'del_18_merge', 'del_5_merge',
       'del_7_merge', 'del_9_merge', 'del_x_merge'],
      dtype='object')

##### Let's confirm that the rules are working with an example where add_merge should be greater than one

##### When Basic

In [25]:
print(d[['del_11p','del_11q','minus11',]].ix[890])
print (deletion['del_11_merge'].ix[890])

del_11p    1.0
del_11q    1.0
minus11    0.0
Name: 890, dtype: float64
2.0

##### When p is missing

In [26]:
print(d[['del_4q','minus4',]].ix[338])
print(d[['del_4q','minus4',]].ix[1049])
print(d[['del_4q','minus4',]].ix[1955])
print()

print (deletion['del_4_merge'].iloc[338])
print (deletion['del_4_merge'].ix[1049])
print (deletion['del_4_merge'].ix[1955])

del_4q    1.0
minus4    1.0
Name: 338, dtype: float64
del_4q    1.0
minus4    1.0
Name: 1049, dtype: float64
del_4q    1.0
minus4    1.0
Name: 1955, dtype: float64

0.0
2.0
2.0

##### When Frequency of minus > 2%

In [27]:
print(deletion[['del_17_merge','minus17']].ix[1204])
print(d.loc[:,['del_17p','del_17q','minus17']].ix[1204])

del_17_merge    1.0
minus17         1.0
Name: 1204, dtype: float64
del_17p    1.0
del_17q    0.0
minus17    1.0
Name: 1204, dtype: float64

##### When Frequency of q and minus > 2%

In [28]:
print(deletion[['del_5_merge','del_5q']].ix[1955])
print(d.loc[:,['del_5p','del_5q','minus5']].ix[1955])

del_5_merge    2.0
del_5q         0.0
Name: 1955, dtype: float64
del_5p    1.0
del_5q    0.0
minus5    1.0
Name: 1955, dtype: float64

##### When Freqency of q > 2%

In [29]:
#print(deletion[['del_9_merge','del_9q']].describe().ix['max'])
print(deletion[['del_9_merge','del_9q']][(deletion.del_9_merge>0) & (deletion.del_9q>0)])
a = d[['del_9p','minus9','del_9q']]
print (a[(a.del_9q>0)&(a.del_9p>0)])
print(a[(a.del_9q>0)&(a.minus9>0)])

Empty DataFrame
Columns: [del_9_merge, del_9q]
Index: []
Empty DataFrame
Columns: [del_9p, minus9, del_9q]
Index: []
Empty DataFrame
Columns: [del_9p, minus9, del_9q]
Index: []

##### When Frequency of minusy > 2%

In [30]:
deletion[['del_x_merge','minusy']].describe().ix['max']
d[['del_xq','minusx','minusy']].describe()
print(d[['del_xq','minusx','minusy']][(d.minusy>0) & (d.minusx>0)])
print(d[['del_xq','minusx','minusy']][(d.minusy>0) & (d.del_xq>0)])

Empty DataFrame
Columns: [del_xq, minusx, minusy]
Index: []
Empty DataFrame
Columns: [del_xq, minusx, minusy]
Index: []

### C) Other high frequency features to introduce

In [31]:
others = df_w_transloc.loc[:,['t_v_11','inv_16','t_8_21','complex']]
others.shape

(2150, 4)

##### Now that we have verify all the rules , we can create the new data frame containing the genetical features and the modified translocation features.

### C) Data Frame with translocations modified

In [32]:
df_final_clustering = df_w_transloc.loc[:,'data_pd':'ZRSR2']
print(df_final_clustering.shape) # 83 genomic features + 2 ids features
df_final_clustering = df_final_clustering.join(add)
print(df_final_clustering.shape) # + 27 translocation addition features
df_final_clustering = df_final_clustering.join(deletion) # + 29 deletion features
print(df_final_clustering.shape)
df_final_clustering = df_final_clustering.join(others) # + 4 deletion features
print('Final df for clustering dimensions :'+str(df_final_clustering.shape))

(2150, 85)
(2150, 112)
(2150, 141)
Final df for clustering dimensions :(2150, 145)

In [33]:
print(df_final_clustering.dtypes.unique())
df_final_clustering.iloc[:,2:] = df_final_clustering.iloc[:,2:].astype(int)
print(df_final_clustering.dtypes.unique())

[dtype('O') dtype('int64') dtype('float64')]
[dtype('O') dtype('int64')]

##### Let's check if there are any columns containing only 0 or 1 to delete them

In [34]:
a=df_final_clustering.describe().T
print(a[a['min']==1])
print(a[a['max']==0])  # we will delete del_18_merge

Empty DataFrame
Columns: [count, mean, std, min, 25%, 50%, 75%, max]
Index: []
               count  mean  std  min  25%  50%  75%  max
del_18_merge  2150.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [35]:
df_final_clustering.drop('del_18_merge',axis=1,inplace=True)

In [36]:
df_final_clustering.shape
df_final_clustering

,data_pd,sample_pd,ASXL1,ASXL2,ASXL3,ATRX,BAGE3,BCOR,BRAF,CBFB,...,del_22_merge,del_17_merge,del_5_merge,del_7_merge,del_9_merge,del_x_merge,t_v_11,inv_16,t_8_21,complex
0,PD20338c,PD20338c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,PD20337c,PD20337c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,PD20336a,PD20336a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,PD20335c,PD20335c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,PD20334a,PD20334a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,PD20333c,PD20333c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,PD20332c,PD20332c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,PD20331a,PD20331a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,PD20330a,PD20330a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,PD20329a,PD20329a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,PD20328a,PD20328a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,PD20327a,PD20327a,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
12,PD20326a,PD20326a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,PD20325a,PD20325a,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
14,PD20324a,PD20324a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,PD20323a,PD20323a,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,PD20322a,PD20322a,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
17,PD20321a,PD20321a,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,PD20320a,PD20320a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,PD20319c,PD20319c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,PD20317a,PD20317a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,PD20316a,PD20316a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,PD20315a,PD20315a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,PD20314a,PD20314a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,PD20313a,PD20313a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,PD20312a,PD20312a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,PD20311c,PD20311c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,PD20309a,PD20309a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,PD20307c,PD20307c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
32,PD22516a,PD22516a,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2394,PD25595a,PD25595a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2395,PD25596a,PD25596a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2396,PD25597a,PD25597a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2397,PD25598c,PD25598c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2398,PD25599a,PD25599a,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2400,PD25601c,PD25601c,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2401,PD25602a,PD25602a,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2402,PD25604c,PD25604c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2403,PD25606c,PD25606c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2404,PD25607c,PD25607c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2405,PD25608a,PD25608a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2406,PD25609c,PD25609c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2407,PD25610c,PD25610c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2408,PD25611a,PD25611a,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2409,PD25612c,PD25612c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2410,PD25613a,PD25613a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2411,PD25614c,PD25614c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2412,PD25615a,PD25615a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2413,PD25616a,PD25616a,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2414,PD25617a,PD25617a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2415,PD25618c,PD25618c,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2417,PD25620c,PD25620c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2418,PD25621a,PD25621a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2419,PD25622a,PD25622a,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2420,PD25623a,PD25623a,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2421,PD25624c,PD25624c,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
2422,PD25625a,PD25625a,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,1
2423,PD25626c,PD25626c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2424,PD25627a,PD25627a,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,1,0,0,1
2426,PD25629c,PD25629c,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1

##### Create the csv file

In [37]:
#df_final_clustering.to_csv("../../../data/updated_dataset/final_clustering.csv",sep=",")